name: core
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #network
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1

  #code generation
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4


  intl: ^0.19.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  test: ^1.25.2
  hive_test: ^1.0.1
  mockito: ^5.4.4