///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsApple = 'assets/icons/apple.svg';
  static const String iconsAppleVec = 'assets/icons/apple.svg.vec';
  static const String iconsGoogle = 'assets/icons/google.svg';
  static const String iconsGoogleVec = 'assets/icons/google.svg.vec';
  static const String iconsImageNotFound = 'assets/icons/image_not_found.svg';
  static const String iconsImageNotFoundVec = 'assets/icons/image_not_found.svg.vec';
  static const String iconsMicrosoft = 'assets/icons/microsoft.svg';
  static const String iconsMicrosoftVec = 'assets/icons/microsoft.svg.vec';
  static const String iconsTesla = 'assets/icons/tesla.svg';
  static const String iconsTeslaVec = 'assets/icons/tesla.svg.vec';

}
