// Mocks generated by Mockito 5.4.4 from annotations
// in local_storage_core/test/repository/local_storage_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:local_storage_core/entity/article_entity.dart' as _i4;
import 'package:local_storage_core/source/data_source.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i2.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addNews(_i4.ArticleEntity? news) => (super.noSuchMethod(
        Invocation.method(
          #addNews,
          [news],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addAllNews(List<_i4.ArticleEntity>? news) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllNews,
          [news],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.ArticleEntity> getAllNews() => (super.noSuchMethod(
        Invocation.method(
          #getAllNews,
          [],
        ),
        returnValue: <_i4.ArticleEntity>[],
      ) as List<_i4.ArticleEntity>);

  @override
  _i3.Future<void> clearBox() => (super.noSuchMethod(
        Invocation.method(
          #clearBox,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
